 #Generated by Django 5.2 on 2025-11-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_route_distance_route_estimated_time_route_stops_and_more"),
        ("buses", "0003_initial_data"),
        ("buses", "0004_bus_driver_contact"),
    ]

    operations = []