# Generated by Django 5.2 on 2025-11-11 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0007_alter_booking_user_alter_payment_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]