# Generated by Django 5.2 on 2025-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0008_alter_schedule_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlysubscription",
            name="seats_reserved",
            field=models.BooleanField(default=False),
        ),
    ]