# Generated by Django 5.2.7 on 2025-11-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0005_add_bus_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={
                "ordering": ["bus_number"],
                "verbose_name": "Bus",
                "verbose_name_plural": "Buses",
            },
        ),
        migrations.AlterModelOptions(
            name="route",
            options={
                "ordering": ["route_name"],
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
            },
        ),
        migrations.RemoveField(
            model_name="bus",
            name="driver_contact",
        ),
        migrations.AddField(
            model_name="route",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="route",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="bus",
            name="bus_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bus",
            name="bus_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="stops",
            field=models.TextField(
                blank=True, default="", help_text="Comma separated bus stops"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]