# Generated by Django 5.2.7 on 2025-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(default='UAP-001', max_length=20, unique=True)),
                ('bus_name', models.CharField(default='Campus Bus', max_length=100)),
                ('capacity', models.IntegerField(default=40)),
                ('driver_name', models.CharField(default='Driver Name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(default='UAP Route', max_length=100)),
                ('start_point', models.CharField(default='UAP Campus', max_length=255)),
                ('end_point', models.CharField(default='City Center', max_length=255)),
                ('fare', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
            ],
        ),
    ]