# Generated by Django 5.2.8 on 2025-11-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver_name',
        ),
    ]
