# Generated by Django 5.2.8 on 2025-11-15 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_monthlysubscription_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlysubscription',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
